on:
    workflow_dispatch:

    push:
        branches:
            - "main"
env:
    PLUGIN_NAME: obsidian-dice-roller

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    release-please:
        runs-on: ubuntu-latest
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
            upload_url: ${{ steps.release.outputs.upload_url }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
            - uses: google-github-actions/release-please-action@v3
              id: release
              with:
                  command: manifest

    upload-build:
        runs-on: ubuntu-latest
        needs: release-please
        if: ${{ needs.release-please.outputs.release_created }}
        env:
            upload_url: ${{ needs.release-please.outputs.upload_url }}
            tag_name: ${{ needs.release-please.outputs.tag_name }}
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "18.x" # You might need to adjust this value to your own version
            - name: Build
              id: build
              run: |
                  npm install
                  npm run build --if-present
                  mkdir ${{ env.PLUGIN_NAME }}
                  cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
                  zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
            - name: Upload zip file
              id: upload-zip
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ env.upload_url }}
                  asset_path: ./${{ env.PLUGIN_NAME }}.zip
                  asset_name: ${{ env.PLUGIN_NAME }}-${{ env.tag_name }}.zip
                  asset_content_type: application/zip
            - name: Upload main.js
              id: upload-main
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ env.upload_url }}
                  asset_path: ./main.js
                  asset_name: main.js
                  asset_content_type: text/javascript
            - name: Upload manifest.json
              id: upload-manifest
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ env.upload_url }}
                  asset_path: ./manifest.json
                  asset_name: manifest.json
                  asset_content_type: application/json
            - name: Upload styles.css
              id: upload-css
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ env.upload_url }}
                  asset_path: ./styles.css
                  asset_name: styles.css
                  asset_content_type: text/css
    notify-obsidian:
        runs-on: ubuntu-latest
        needs: upload-build
        steps:
            - name: Webhook
              uses: javalent/workflows/actions/discord-embed@main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: Dice Roller
                  repo: dice-roller
                  webhook-urls: ${{ secrets.OBSIDIAN_WEBHOOK }}
    notify-ttrpg:
        runs-on: ubuntu-latest
        needs: upload-build
        steps:
           - name: Webhook
             uses: javalent/workflows/actions/discord-embed@main
             env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
             with:
                 name: Dice Roller
                 repo: dice-roller
                 webhook-urls: ${{ secrets.TTRPG_WEBHOOK }}
    publish:
        needs: release-please
        if: ${{ needs.release-please.outputs.release_created }}
        uses: javalent/workflows/.github/workflows/publish.yml@main
        secrets: inherit
